#!/bin/bash

shopt -s extglob


usage() {
        cat <<EOF
        Opções:
        1 ------------ Estender a tela para a direita
        2 ------------ Estender a tela para a esquerda
        3 ------------ Utilizar apenas o monitor principal
        4 ------------ Mudar o brilho do computador
	5 ------------ Configurar corretamente o touchpad
	6 ------------ Explicacão sobre o comando anterior
        7 ------------ Abre essa mensagem

* Mt alves 
EOF
}


case $1 in

1) xrandr --auto --output eDP-1-1 --right-of HDMI-1-1;;

2) xrandr --auto --output eDP-1-1 --left-of HDMI-1-1;;

4) xrandr --output eDP-1-1 --brightness $2;; 

3) xrandr --auto --output eDP-1-1 ;;

5) xinput set-prop 'Elan Touchpad' 'libinput Tapping Enabled' 1;;

6) echo "Substitua a primeira variável pelo seu hardware";;

*) usage
	
esac

